spring: 
  datasource:    
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
  jpa:    
    open-in-view: false
    hibernate:
      ddl-auto: validate
bruno:
  openapi:
    dev-url: http://localhost:8080
    prod-url: https://santander-api-2023-prd.up.railway.app                     
          